package view;

import javax.swing.JOptionPane;
import helper.PedidoHelper;
import view.PedidoGUI;

/**
 *
 * @author Paloma
 */
public class Menu extends javax.swing.JFrame {

    private ProdutoGUI produtoGUI;
    private PedidoGUI pedidoGUI;
    private PedidoHelper pedidoHelper;
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        setLocationRelativeTo(null);
        pedidoHelper = PedidoHelper.getInstance();
        this.setTitle("Software Gerenciarejo");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuControlClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuControlPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuControlProdutos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 153));
        setFocusable(false);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(1366, 769, 769, 769));
        setMinimumSize(new java.awt.Dimension(1366, 769));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo-.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 440, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_tela-.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setText("Bem vindo ao Sistema de Gerenciamento de Varejo!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_note.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 790));

        jMenuBar1.setBackground(new java.awt.Color(100, 100, 100));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1366, 769));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1366, 769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(324, 42));

        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/casa.png"))); // NOI18N
        menuInicio.setText("Início");

        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/info.jpg"))); // NOI18N
        MenuSobre.setText("Sobre");
        MenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreActionPerformed(evt);
            }
        });
        menuInicio.add(MenuSobre);

        MenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        menuInicio.add(MenuSair);

        jMenuBar1.add(menuInicio);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/pessoas.png"))); // NOI18N
        jMenu4.setText("Cliente");

        MenuControlClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/add user.jpg"))); // NOI18N
        MenuControlClientes.setText("Controle Clientes");
        MenuControlClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlClientesActionPerformed(evt);
            }
        });
        jMenu4.add(MenuControlClientes);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/pedido.jpg"))); // NOI18N
        jMenu2.setText("Pedidos");

        MenuControlPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/pedidos.png"))); // NOI18N
        MenuControlPedidos.setText("Controle Pedidos");
        MenuControlPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(MenuControlPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/controle_produto.png"))); // NOI18N
        jMenu3.setText("Produtos");

        MenuControlProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/prod.png"))); // NOI18N
        MenuControlProdutos.setText("Controle Produtos");
        MenuControlProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuControlProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(MenuControlProdutos);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/categoria.png"))); // NOI18N
        jMenu6.setText("Categoria");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/categoria.png"))); // NOI18N
        jMenuItem1.setText("Controle de Categorias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja Sair?", "Menu Principal", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.OK_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuControlPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlPedidosActionPerformed
        if (pedidoGUI == null) {
            pedidoGUI = new PedidoGUI(this, true);
            // pedidoGUI.setSize(600, 400);
        }
        pedidoGUI.setVisible(true);
        

    }//GEN-LAST:event_MenuControlPedidosActionPerformed

    private void MenuControlProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlProdutosActionPerformed
        if (produtoGUI == null) {
            produtoGUI = new ProdutoGUI(this, true);
            //  produtoGUI.setSize(600, 400);
        }
        produtoGUI.getComboBoxPedidos().setModel(new javax.swing.DefaultComboBoxModel(pedidoHelper.getCodigos()));
        produtoGUI.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuControlProdutosActionPerformed

    private void MenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreActionPerformed
    }//GEN-LAST:event_MenuSobreActionPerformed

    private void MenuControlClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuControlClientesActionPerformed
        CadastrarCliente cadastrar = new CadastrarCliente();
        cadastrar.setVisible(true);
        //cadastrar.setAlwaysOnTop(true);
        cadastrar.setLocationRelativeTo(null);
        
        this.dispose();
        
    }//GEN-LAST:event_MenuControlClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AdicionarCategoria categoria = new AdicionarCategoria();
        categoria.setVisible(true);
        categoria.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuControlClientes;
    private javax.swing.JMenuItem MenuControlPedidos;
    private javax.swing.JMenuItem MenuControlProdutos;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenuItem MenuSobre;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuInicio;
    // End of variables declaration//GEN-END:variables
}
