package view;

import javax.swing.JOptionPane;
import classes.ProdutoVO;
import classes.PedidoVO;
import helper.PedidoHelper;

/**
 *
 * @author paloma
 */
public class PedidoGUI extends javax.swing.JDialog {

    private PedidoHelper pedidoHelper;

  
    public PedidoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pedidoHelper = PedidoHelper.getInstance();
        this.setTitle("Controle de Pedidos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lbldescricao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(210, 310, 130, 22);

        lblID.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblID.setText("Id do pedido:");
        lblID.setFocusable(false);
        getContentPane().add(lblID);
        lblID.setBounds(100, 310, 104, 17);
        getContentPane().add(txtdescricao);
        txtdescricao.setBounds(210, 360, 130, 22);

        btnPesquisar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(410, 290, 90, 30);

        btnAdd.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnAdd.setText("Incluir");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(410, 330, 90, 30);

        btnAlterar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(410, 370, 90, 30);

        btnExcluir.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(410, 410, 90, 30);

        lbldescricao.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbldescricao.setText("Descrição:");
        getContentPane().add(lbldescricao);
        lbldescricao.setBounds(120, 360, 80, 17);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 244, 37, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolsa_de_compras-.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 70, 200, 200);

        btnvoltar.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnvoltar.setText("Voltar");
        btnvoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(410, 450, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_pedidos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 600, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
          try{
            Long id = Long.parseLong(txtId.getText());
            PedidoVO pedidoVO = pedidoHelper.pesquisarPedido(id);
            
            if (pedidoVO!=null)
            {
                txtdescricao.setText(pedidoVO.getDescricao());
            }
            else{
                JOptionPane.showMessageDialog(this, "Registro não encontrado!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Valor de id inválido!");
        }
      
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Long id = 0l;
        String descricao = null;
        int quantidade = -1;

        try {
            if (txtId.getText() == null || txtId.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Id é obrigatório!");
            } else {
                id = Long.parseLong(txtId.getText());
                descricao = txtdescricao.getText();

                PedidoVO temp = new PedidoVO( id, descricao);

                quantidade = pedidoHelper.adicionarPedido(temp);

                if (quantidade > 0) {
                    JOptionPane.showMessageDialog(this, "Pedido incluído com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Pedido não foi incluído!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Valor de Id inválido!");
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Long id = 0l;
        String descricao = null;
        int quantidade = -1;
        PedidoVO pedidoVO = null;

        try {
            if (txtId.getText() == null || txtId.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Id é obrigatório!");
            } else {
                id = Long.parseLong(txtId.getText());
                descricao = txtdescricao.getText();

                pedidoVO = pedidoHelper.pesquisarPedido(id);

                if (pedidoVO != null) {
                    pedidoVO.setDescricao(descricao);
                    JOptionPane.showMessageDialog(this, "Pedidos(s) alterado(s) com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Pedidos(s) não encontrado(s)!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Valor de Id inválido!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int quantidade = 0;
        Long  id = 0l;
        PedidoVO produto = null;

        try {
            if (txtId.getText() == null || txtId.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Id obrigatório!");
            } else {
                id = Long.parseLong(txtId.getText());
                quantidade = pedidoHelper.removerPedido(new PedidoVO(id));  // Exclui os pedidos
                if (quantidade > 0) {
                    JOptionPane.showMessageDialog(this, "Pedidos(s) excluído(s) com sucesso!");
                    txtId.setText(" ");
                    txtdescricao.setText(" ");
                } else {
                    JOptionPane.showMessageDialog(this, "Pedidos(s) não encontrado(s)!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Valor de Id inválido!");
        }                // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PedidoGUI dialog = new PedidoGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtdescricao;
    // End of variables declaration//GEN-END:variables
}
